### ISSUE TITLE
Changing pivot extra attributes

### ISSUE THREAD

**Issue by Pab89** [fico7489/LaravelPivot#13]
Hi, i downloaded this package to help me update a position column on my pivot table. Bassicly when the pivotAttaching, pivotDetaching, pivotUpdating are fired i will calculate the correct position and assign it to the pivot. I cant seem to figure out how to update the $pivotIdsAttributes so when the pivot is created it gets the new position calculated within pivotAttaching. Is this possible ?

**Comment by fico7489** [comment]
You probably want to update position only when the pivot is added(pivotAttaching) or deleted(pivotDetaching), why you need to update position when the pivot is updated(pivotUpdating )?

**Comment by Pab89** [comment]
Well if the position is updated i need to change it for all others to, but that is actually quite easy. The main problem for me is when the pivot is attached then i need a way to say that when its created it should have this position. Example the pivot being created should have position 5 when created.

**Comment by lewisf2001uk** [comment]
@Pab89 I don't believe the package does what you are wanting. Whatever is passed to the attach method is passed to the Laravel framework in the same way. Updating the $pivotIdsAttributes within the event listener won't do anything.
Can you provide a bit of example code of what exactly you are trying to achieve?

**Comment by fico7489** [comment]
@Pab89  you probably want something like this : 

```
    static RECALCULATE = true;

    static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        if(self::RECALCULATE){
            self::recalculatePositions($model, $relationName);
        }
    });
    
    static::pivotDetached(function ($model, $relationName, $pivotIds) {
        if(self::RECALCULATE){
            self::recalculatePositions($model, $relationName);
        }
    });
    
    static::pivotUpdated(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        if(self::RECALCULATE){
            self::recalculatePositions($model, $relationName);
        }
    });
    
    private static function recalculatePositions(){
        $i = 1;
        self::RECALCULATE = false;
        foreach($model->$relationName as $relation){
            $model->$relationName()->updateExistingPivot($relation->pivot_id, ['position' => $i]);
            $i++;
        }
        self::RECALCULATE = true;
    }
```

note: this is just an quick example and it is not tested and verified, but can give you a direction...

**Comment by Pab89** [comment]
Thanks for all the quick answers, your approach could definitely work, i would prefer though doing it while in "pivotAttaching" to save the extra mysql call. I would prefet something like this:

```
static::pivotAttaching( function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            $highestCurrentPosition = collect($model->$relationName->toArray())->pluck('pivot')->pluck('position')->sort()->last();
            $newPosition = $highestCurrentPosition + 1;
            $pivotBeingCreated->position = $newPosition;

});
```

Where the missing piece is how to get "pivotBeingCreated". Hope i can be done else i will go with your approach

**Comment by fico7489** [comment]
You actually can attach more pivots at once, but I suppose in your app will be only one at the time if so you don't need a loop like in my case. You probably want something like this : 

```
$firstPivotIdInArray = array_keys($pivotIdsAttributes)[0]);
$pivotBeingCreated = $model->$relationName->wherePivot('pivot_id', '=', $firstPivotIdInArray );
```

**Comment by Pab89** [comment]
Exactly only problem is that i want to do it before its created. ;) While "attaching" at this time the pivot dosen't exists

**Comment by fico7489** [comment]
oh I see you problem now, if you want to do that you need to implement your belongsToMany relation and override attach, detach and updateExistingPivot functions like this : 

this is original from this package : 
```
    public function attach($ids, array $attributes = [], $touch = true)
    {
        list($idsOnly, $idsAttributes) = $this->getIdsWithAttributes($ids, $attributes);
        $this->parent->fireModelEvent('pivotAttaching', true, $this->getRelationName(), $idsOnly, $idsAttributes);
        parent::attach($ids, $attributes, $touch);
        $this->parent->fireModelEvent('pivotAttached', false, $this->getRelationName(), $idsOnly, $idsAttributes);
    }
```

you need something like this : 

    public function attach($ids, array $attributes = [], $touch = true)
    {
        list($idsOnly, $idsAttributes) = $this->getIdsWithAttributes($ids, $attributes);

        $position = $this->calculatePosition(params);
        $attributes['position'] =  $position ;

        $this->parent->fireModelEvent('pivotAttaching', true, $this->getRelationName(), $idsOnly, $idsAttributes);
        parent::attach($ids, $attributes, $touch);
        $this->parent->fireModelEvent('pivotAttached', false, $this->getRelationName(), $idsOnly, $idsAttributes);
    }

**Comment by fico7489** [comment]
@lewisf2001uk  if attach look like this : 

parent::attach($idsAttributes, [], $touch);

he could just

**Comment by fico7489** [comment]
@lewisf2001uk  maybe we can add solution for this in package : 

    public function attach($ids, array $attributes = [], $touch = true)
    {
        list($idsOnly, $idsAttributes) = $this->getIdsWithAttributes($ids, $attributes);

        $attributes = $this->getParent()->changeAttributes(params);

        $this->parent->fireModelEvent('pivotAttaching', true, $this->getRelationName(), $idsOnly, $idsAttributes);
        parent::attach($ids, $attributes, $touch);
        $this->parent->fireModelEvent('pivotAttached', false, $this->getRelationName(), $idsOnly, $idsAttributes);
    }

with this solution he could only override changeAttributes() function in model.

**Comment by lewisf2001uk** [comment]
@fico7489 Yeah that could work. We would need to do an `if` to check if the function exists.
I'm a little confused with what @Pab89 is exactly trying to achieve, as `$model->$relationName->toArray()` will be a database call anyway.
So wouldn't this be best to be done where the attach method is being called passing the pivot directly to the attach method? (All done within the base Laravel Framework)

**Comment by fico7489** [comment]
`$model->$relationName->toArray()`

what if data is eager loaded ? 

we can create dummy method in trait

```
function changeAttributes(params, $attributes){
     return $attributes;
}
```

Which could be overridden in models...

**Comment by lewisf2001uk** [comment]
Yeah my mistake, I didn't think about if it was eager loaded.
I like the idea.
We would need to give it a think though, as effectively to make it usable on all circumstances we would most likely have to change what is passed to the `parent::attach($ids, $attributes, $touch);` line.

For instance when
`$user->roles()->attach([1 => ['value' => 123], 2 => ['value' => 456]], ['value2' => 789]);`
$attributes for
```
function changeAttributes(params, $attributes){
     return $attributes;
}
```
would be just be `['value2' => 789]`.

It can't hurt to have the extra functionality though!

**Comment by Pab89** [comment]
Thanks all the responses it would be really great to see that functionality implemented. I could se a lot of use cases where you would want to "transform" or add some additional attributes while the pivot is being created. :)

**Comment by fico7489** [comment]
closing...

**Comment by MostafaNobaghi** [comment]
> Thanks all the responses it would be really great to see that functionality implemented. I could se a lot of use cases where you would want to "transform" or add some additional attributes while the pivot is being created. :)

is this functionality available now? i didnt understand how to use this.
i just want to add an extra attribute to attributes array before update (in pivotUpdating event)

**Comment by fico7489** [comment]
@MostafaNobaghi you can do it, see my responses from above

**Comment by MostafaNobaghi** [comment]
@fico7489 
Thanks for the response
i read the responses but i couldn't figure it out.
this is my code:

```
class Organization extends Authenticatable implements JWTSubject
{
    use PivotEventTrait;


    public static function boot()
    {
        parent::boot();

        static::pivotUpdating(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            $pivotId = $pivotIds[0];

            if ($pivotIdsAttributes[$pivotId]['status'] === 5) {
                /****  IF CONDTION WAS TRUE I WANT ADD TO ATTRBUTES BEFORE UPDATING PIVOT (SO I CAN QUERY ONCE) ****/
                $pivotIdsAttributes[$pivotId]['is_primary'] = 1;
            }
            event(new ChangeOrganizationUserPivotStatus($model, $relationName, $pivotIds[0], $pivotIdsAttributes[$pivotId]));
            
        });
```

can you give me a tip?
i didn't find any changeAttributes() method or using of it in package to figure out how to use that

**Comment by fico7489** [comment]
pivotUpdating is not triggered when pivot is attached, you must cover both cases:

```
    static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        self::doSomethingWithPivot($pivotIds);
    });
    
    static::pivotUpdated(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        self::doSomethingWithPivot($pivotIds);
    });
    
    private static function doSomethingWithPivot($pivotIds){
        $pivots = \DB::table('PIVOT_TABLE')->whereIn('id', $pivotIds)->get();
		
        //NOW you have pivots, do something with them :)
    }
```
