### ISSUE TITLE
Sync Event

### ISSUE THREAD

**Issue by taranom73** [fico7489/LaravelPivot#16]
Hi

I need to use the sync event, your example for sync is not working , Could you please make a full example of what I need to do?

The following code just don't work, Do I need to define a custom function for my static definitions .  static::pivotAttached,  static::pivotUpdated,...?

Best

`class User extends Model
{
    use PivotEventTrait;
    ....
    
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }
    
    static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        echo 'pivotAttached';
        echo get_class($model);
        echo $relationName;
        print_r($pivotIds);
        print_r($pivotIdsAttributes);
    });
    
    static::pivotUpdated(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        echo 'pivotUpdated';
        echo get_class($model);
        echo $relationName;
        print_r($pivotIds);
        print_r($pivotIdsAttributes);
    });
    
    static::pivotDetached(function ($model, $relationName, $pivotIds) {
        echo 'pivotDetached';
        echo get_class($model);
        echo $relationName;
        print_r($pivotIds);
    });

...
class Role extends Model
{
    ....
`

**Comment by fico7489** [comment]
can you paste code where you call sync() ?and your models code ?

**Comment by taranom73** [comment]
public function ajaxStore(Request $request) {
        $jobpositions = $request->input('jobposition');
        $recruiterEmploymentAd = new RecruiterEmploymentAd ();
        $recruiterEmploymentAd->fill($request->all());
        $recruiterEmploymentAd->user_recruiters_id = Auth::id();
        $recruiterEmploymentAd->user_id = Auth::id();
        $recruiterEmploymentAd->save();
        $recruiterEmploymentAd->jobPositions()->sync($jobpositions);

        $recruiterEmploymentAds = RecruiterEmploymentAd::latest()->where('user_recruiters_id', '=', Auth::id())->with('userrecruiter','useraccount','recruiteremploymentadsjobpositions')->paginate(25);

        return view(*', compact('recruiterEmploymentAds'));
    }

**Comment by fico7489** [comment]
you must use trait

`use PivotEventTrait;`

in recruiterEmploymentAd model, also put this there : 

```
public static function boot()
{
    parent::boot();

    static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        echo 'pivotAttached';
    });
    
    static::pivotDetached(function ($model, $relationName, $pivotIds) {
        echo 'pivotDetached';
    });
    
    static::pivotUpdated(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        echo 'pivotUpdated';
    });
}
```

**Comment by taranom73** [comment]
It works, thank's a lot!
