### ISSUE TITLE
fireEventModel having different payload than usual

### ISSUE THREAD

**Issue by arukompas** [fico7489/LaravelPivot#17]
Tell me if I'm wrong, but I believe there's an issue with the extended `fireModelEvent` function.

The new method dispatches the event with a custom payload:

```php
$payload = ['model' => $this, 'relation' => $relationName, 'pivotIds' => $ids, 'pivotIdsAttributes' => $idsAttributes];
```

instead of the regular `$this` object.

Wouldn't this also affect other regular events like `updated`, `saved`, etc.. ?

This code below would no longer work after including the trait:

```php
public static function boot()
{
    static::updated(function($model) {
        \Log::info("Model ID {$model->id} has been updated!");
    });
}
```

**Comment by fico7489** [comment]
there is a test for normal events https://github.com/fico7489/laravel-pivot/blob/master/tests/PivotEventTraitTest.php#L265

**Comment by arukompas** [comment]
Yes, this checks for the regular events to be fired away, but it doesn't check for the payload to be exactly the same as it used to be BEFORE adding the trait.

If someone's got a huge codebase with loads of model event listeners in place, they would have to change all of those listeners if they want to include your trait.

```php
public static function boot()
{
    static::updated(function($model) {
        \Log::info("Model ID {$model->id} has been updated!");
    });
}
```

would have to become this:
```php
public static function boot()
{
    static::updated(function($payload) {
        \Log::info("Model ID {$payload['model']->id} has been updated!");
    });
}
```

**Comment by fico7489** [comment]
I just tested now, my BaseModel code : 

```
abstract class BaseModel extends Model
{
    use PivotEventTrait;
    
   //...

    public static function boot()
    {
        parent::boot();

        static::updated(function ($model) {
            echo "Model ID {$model->id} updated!<br/>";
        });

        static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            echo "Model ID {$model->id} pivotAttached!<br/>";
        });
    }
```

my controller code : 

 ```
   public function index()
    {
        $user = App\Models\User::find(11);
        $user->update(['google_id' => random_int(100, 1000000)]);
        $user->roles()->sync([]);
        $user->roles()->sync([1]);
        exit;
```

output is : 

```
Model ID 11 updated!
Model ID 11 pivotAttached!
```

**Comment by arukompas** [comment]
Nevermind, my mistake! I did not check for the function arguments with the pivot trait included :)

It works, I should've tested it first before writing this :)

Sorry
