### ISSUE TITLE
Implementing gives me an error (Call to undefined method App\Providers\AppServiceProvider::registerModelEvent())

### ISSUE THREAD

**Issue by ivaralink** [fico7489/LaravelPivot#20]
My app service provider is
```
<?php
namespace App\Providers;

use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Auth;

use App\Models\User;
use App\Services\Log\ImportLogWriter;
use Illuminate\Support\Facades\Schema;

use App\Models\ProjectPhaseDocumentTopic;
use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
use Illuminate\Database\Eloquent\Model;

class AppServiceProvider extends ServiceProvider
{   
    use PivotEventTrait;
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {   
        \App::setLocale('nl');
        Schema::defaultStringLength(191);
        
        static::pivotUpdated(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            echo 'pivotUpdated';
            echo get_class($model);
            echo $relationName;
            print_r($pivotIds);
            print_r($pivotIdsAttributes);
        });
    }
}
```

Gives me a error:
Call to undefined method App\Providers\AppServiceProvider::registerModelEvent()

If i do not implement the trait here it gives me:
Call to undefined method App\Providers\AppServiceProvider::pivotUpdated()

Do you know what i am doing wrong?

**Comment by fico7489** [comment]
above code should go to **base model,** not **AppServiceProvider**...

**Comment by ivaralink** [comment]
but you write also:

public static function boot()
{
    parent::boot();

    static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        //
    });
}

this is to catch the event am i right?

in app service provider?

**Comment by fico7489** [comment]
read this and you will understand then https://laracasts.com/discuss/channels/eloquent/listen-to-any-saveupdatecreate-event-for-any-model

**Comment by ivaralink** [comment]
Yes, i have it working, thanks for your help!
