### ISSUE TITLE
Detach method breaks when called without arguments

### ISSUE THREAD

**Issue by joostbaptist** [fico7489/LaravelPivot#21]
First of all, thank you for creating this package. 

I found that this package breaks the detach method when it is called without any arguments. For example,`$user->roles()->detach()` would not actually drop any rows from the pivot table. The reason is that the signature of the detach method does not match that of Laravel's detach method. Compare https://github.com/fico7489/laravel-pivot/blob/master/src/Relations/BelongsToManyCustom.php#L35 with https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L356. Specifically, the `$ids` attribute receives null as a default value in Laravel, but in this package it's an empty array, so no rows are actually deleted. 

I propose to fix this issue by changing the method signature to match Laravel's and and to check if `$ids` is null, and if it is,  to perform a query that looks up all of the IDs that should be detached. See my PR.

**Comment by fico7489** [comment]
Thanks for the catch.

In laravel 5.4. detach method is changed from

`public function detach($ids = [], $touch = true)`

to : 

`public function detach($ids = null, $touch = true)`

I merged you changes to 2.0, 2.1 and master branch of this package.

**Comment by joostbaptist** [comment]
Thanks for merging! 👍
