### ISSUE TITLE
Using this in obsevers

### ISSUE THREAD

**Issue by HiradRoshandel** [fico7489/LaravelPivot#23]
Is there a way to use this inside my observer class? I don't wanna put these functions inside my model since it separates the logic. Ideal use case:
```
class Myobserver 
{
    public function pivotAttaching($model, $relationName, $pivotIds, $pivotIdsAttributes) {
    ...
    }
}
```

**Comment by lewisf2001uk** [comment]
I think it should work (I've not tested it), but the observablesEvents array is updated in the package.
Just make sure you include the `PivotEventTrait` trait in your base model.
Let me know how you get on.

**Comment by fico7489** [comment]
@aconital  see in documentation : 

```
//You can also see those events here :

\Event::listen('eloquent.*', function ($eventName, array $data) {
    echo $eventName;  //e.g. 'eloquent.pivotAttached'
});
```

**Comment by HiradRoshandel** [comment]
@fico7489 But where do I put that in my observer?
@lewisf2001uk no it didn't work

**Comment by fico7489** [comment]
@aconital  I think that your question is not about how to use this package, I think that your question is how to use observers in laravel, anyway here is documentation 
https://laravel.com/docs/5.6/eloquent#observers

you need something like this : 

```
ObserverServiceProvider{
    ...
    self::$userObserver = new UserObserver();
    User::observe(self::$userObserver);
}

class UserObserver{
    public function pivotAttached($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        exit('here I am ...');
    }
```

**Comment by HiradRoshandel** [comment]
@fico7489 The issue was that I'm using **morphToMany**  for my relationship and the library doesn't support it. Would be cool if this functionality is added

**Comment by fico7489** [comment]
@aconital morphToMany  support added
