### ISSUE TITLE
Bug in results of sync() call

### ISSUE THREAD

**Issue by samansmink** [fico7489/LaravelPivot#25]
When using the PivotEventTrait on my Model, the following call results in unexpected behaviour.
Im trying to update a pivot table column on an existing pivot.

```
$result = $model->relation()->sync([24 => ['rank' => 10]]))

print_r($result)
```

With the trait enabled on Model the result is:

`Array ( [attached] => Array ( ) [detached] => Array ( ) [updated] => Array ( ) )`

but with the trait disabled its

`Array ( [attached] => Array ( ) [detached] => Array ( ) [updated] => Array ( [0] => 24 ) )`

Currently the attach/detach/updateExistingPivot functions do not return the result of their parent calls.  
i think simply returning the results of the parent call in updateExistingPivot() will solve the problem, since it is used in the code from the `attachNew()` function of the original `InteractsWithPivotTable`, see snippet below:

```
elseif (count($attributes) > 0 &&
                $this->updateExistingPivot($id, $attributes, $touch)) {
                $changes['updated'][] = $this->castKey($id);
            }
```

**Comment by samansmink** [comment]
Just tested it and it indeed seems to be the solution:

change 
```
public function updateExistingPivot($id, array $attributes, $touch = true)
    {
        list($idsOnly, $idsAttributes) = $this->getIdsWithAttributes($id, $attributes);

        $this->parent->fireModelEvent('pivotUpdating', true, $this->getRelationName(), $idsOnly, $idsAttributes);
        parent::updateExistingPivot($id, $attributes, $touch);
        $this->parent->fireModelEvent('pivotUpdated', false, $this->getRelationName(), $idsOnly, $idsAttributes);
    }
```

to

```
public function updateExistingPivot($id, array $attributes, $touch = true)
    {
        list($idsOnly, $idsAttributes) = $this->getIdsWithAttributes($id, $attributes);

        $this->parent->fireModelEvent('pivotUpdating', true, $this->getRelationName(), $idsOnly, $idsAttributes);
        $parentResult = parent::updateExistingPivot($id, $attributes, $touch);
        $this->parent->fireModelEvent('pivotUpdated', false, $this->getRelationName(), $idsOnly, $idsAttributes);

        return $parentResult;
    }
```

And the same holds for detach & attach although they dont interfere with sync() the way updateExistingPivot does currently

**Comment by fico7489** [comment]
@samansmink  you are right! Do you maybe want to create PR ? If no I will push fix soon...

**Comment by samansmink** [comment]
sure

**Comment by fico7489** [comment]
merged! thanks!
