### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by chriz74x** [fico7489/LaravelPivot#27]
Hello, how can you use these newly created events with Notifications? I tried to create an observer for pivotAttached but when I try to pass a second argument to the observer other then the User I get an error: expected instance of model, string given. In my Notification I am using the model and the observer whines that I am passing a string so my guess is that your pivotAttached() event is outputting something into the observer but what? Or how is it behaving?

**Comment by ctf0** [comment]
@chriz74x can u add some code ?

**Comment by chriz74x** [comment]
ok, let's say this is the notification:

```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;

use App\User;
use App\Collected_item;

class ModelCollected extends Notification implements ShouldQueue
{
    use Queueable;

    protected $following;
    protected $collected_item;


    /**
     * ModelCollected constructor.
     * @param User $following
     * @param Collected_item $Collected_item
     */
    public function __construct(User $following, Collected_item $Collected_item)
    {
        $this->following = $following;
        $this->Collected_item = $collected_item;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['database'];
    }

    /**
     * @param $notifiable
     * @return array
     */
    public function toDatabase($notifiable)
    {
        return [
            'following_id' => $this->following->id,
            'following_name' => $this->following->username,
            'Collected_item_id' => $this->collected_item->id,
            'model_id' => $this->collected_item->model_id
        ];
    }


}
```

This should be the observer 
```
<?php


namespace App\Observers;

use App\Notifications\ModelCollected;
use App\Collected_item;
use App\User;


class ModelCollectedObserver
{
    public function pivotAttached(User $user, Collected_item $collected_item)
    {
       
       //bla bla do something

    }
}
```

**Comment by fico7489** [comment]
@chriz74x

1.I can't see in your example where are you doing sync, attach or detach ...
2.Did you manage to successfull use laravel observers without this package 
https://laravel.com/docs/5.6/eloquent#observers
?

**Comment by chriz74x** [comment]
I am attaching in my collection controller like this:

```
$user->collected_item()->attach([$item->id => ['collected_item_data' => $data]]);
```

Yes I can use observers for model events without this package.

**Comment by fico7489** [comment]
why : 

```
    public function pivotAttached(User $user, Collected_item $collected_item)
    {
       //
    }

```
why not 

```
    static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        //
    });
```

like you see in docs ?

can you first try example from here 
https://laracasts.com/discuss/channels/eloquent/listen-to-any-saveupdatecreate-event-for-any-model
to understand concept ?

**Comment by chriz74x** [comment]
Because the notification that you can see in the code I added is using User and Collected_item in the construct and the observer expects to have those models to fire the notification. At least that is the normal behavior with eloquent events, notifications and observers.

**Comment by fico7489** [comment]
you need 

1.this

```
    public function pivotAttached($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        //
    }
```

in UserObserver
this concept : https://laravel.com/docs/5.6/eloquent#observers


2.or you can put this 

```
    static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        //
    });

```

in user model
this concept : https://laracasts.com/discuss/channels/eloquent/listen-to-any-saveupdatecreate-event-for-any-model

**Comment by chriz74x** [comment]
I can't use the User model because that won't discriminate between many to many relationships. I mean you can't observe the User you have to observe the collected_item.
Anyway I tried what you suggest, nothing comes out of observer. I don't think you can easily create a notification based on this package. The events you are dispatching seem non standard. Please if I am wrong try and create a notification based on this standard idea using one of the package events: https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/9

**Comment by fico7489** [comment]
observer is observing model, but laravel many to many relation is not using model for pivot table, that is actually the reason why this package exists, otherwise you would just observe model of collected_item db table and you won't need this package...I tell you you need user observer...

**Comment by chriz74x** [comment]
FYI I was able to make notifications work with this observer:

```
namespace App\Observers;

use App\Notifications\ModelCollected;
use App\Collected_item;

class UserObserver
{


    public function pivotAttached($user, $relationName, $pivotIds)
    {


        if ($relationName == 'collected_item') {

            //gets the Collected_item model
            $item = Collected_item::find($pivotIds)->first();

            //fires notifications
            foreach ($user->followers as $follower) {
                $follower->notify(new ModelCollected($user, $item));
            }

        }

    }

}
```
