### ISSUE TITLE
diff with eloquent-extra-events

### ISSUE THREAD

**Issue by ctf0** [fico7489/LaravelPivot#3]
can u plz tell me whats is the diff between this package and https://github.com/neylsongularte/eloquent-extra-events ?

**Comment by fico7489** [comment]
I really did not know about that package, now I looked at it and : 

1.this package does not have tests, my have
2.my package have better and more comprehensive documentation with real example
3.this package does not have static model hook methods
4.this package does not cover updateExistingPivot()
5.this package  overwrite some laravel code in belongsToMany() relation

feel free to chose...

**Comment by ctf0** [comment]
awesome, thanx

**Comment by fico7489** [comment]
feel free to request enhancements...

**Comment by ctf0** [comment]
i have a couple of repos 
https://github.com/ctf0/Odin
https://github.com/ctf0/SimpleMenu

which both needs pivot ops, will try with them and see what will come up.
