### ISSUE TITLE
Retrieve pivot original data

### ISSUE THREAD

**Issue by akatche** [fico7489/LaravelPivot#30]
Hi! I want to know if its possible to get the pivot table original data, something similar to the method $model->getOriginal() that it can be used on a normal observer.
Thanks!

**Comment by fico7489** [comment]
no with ->getOriginal(), because laravel is not using model for pivot data for sync, attach and detach.

**Comment by fico7489** [comment]
in $pivotIdsAttributes variable in pivotUpdating event you have info what will be changed, you can get current values based on $pivotIds : 

select  from pivot table where id pivot_in =  $pivotIds

**Comment by MostafaNobaghi** [comment]
Hi thanks for this great package.
I need this too. (for updateExistingMethod) aand i have multiple pivot with same foreign keys but different "status" like below:

user_class table
<table>
  <tr>
    <th>id</th>
    <th>user_id</th>
    <th>class_id</th>
    <th>status</th>
    <th>and some date columns</th>
  <tr>
  
  <tr>
    <td>1</td>
    <td>1</td>
    <td>2</td>
    <td>1</td>
    <td> some date columns</td>
  <tr>
  <tr>
    <td>2</td>
    <td>1</td>
    <td>2</td>
    <td>2</td>
    <td> some date columns</td>
  <tr>
  <tr>
    <td>3</td>
    <td>1</td>
    <td>2</td>
    <td>5</td>
    <td> some date columns</td>
  <tr>
    <td>4</td>
    <td>1</td>
    <td>2</td>
    <td>5</td>
    <td> some date columns</td>
  <tr>
  
</table>

so i cant use your suggestion

is there another suggestion or anything you can do?
