### ISSUE TITLE
pivotIds - what do they refer to?

### ISSUE THREAD

**Issue by amadeann** [fico7489/LaravelPivot#31]
Thanks for a very useful package.

I'm using the 'pivotAttached' method in my observer. I assumed that 'pivotIds' variable passed to the event refers to the id in the pivot table (not models related through the pivot table). However, from what I see, that id refers to the id of related model, and not the row id in the pivot table. Is it the expected behavior, or a bug?

**Comment by fico7489** [comment]
this is normal/expected  behavior ...
