### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by rogervila** [fico7489/LaravelPivot#32]
Hello,

Could it be possible to [downgrade the minimum laravel version to 5.5](https://github.com/fico7489/laravel-pivot/blob/master/composer.json#L26)?

Thank you very much.

**Comment by lewisf2001uk** [comment]
Filip is actually keeping the package available for multiple versions of Laravel already, see "Version Compatibility" on the readme.

**Comment by fico7489** [comment]
jusr run composer require fico7489/laravel-pivot:"*"
this command will install appropriate package version for your laravel version, 5.5.* in your case...
