### ISSUE TITLE
package fails on MorphToMany relations

### ISSUE THREAD

**Issue by ctf0** [fico7489/LaravelPivot#33]
> laravel: 5.5
> package: 2.1.6

hi there, i found the issue while using 2 diff packages

> https://github.com/spatie/laravel-permission **"detach"**

https://github.com/spatie/laravel-permission/blob/0e0fba29758b892da94b62c5cb3250b1cc04fd41/src/Traits/HasRoles.php#L117-L122

https://github.com/spatie/laravel-permission/blob/0e0fba29758b892da94b62c5cb3250b1cc04fd41/src/Traits/HasPermissions.php#L237-L242

> https://github.com/spatie/laravel-tags **"sync"**

https://github.com/spatie/laravel-tags/blob/5d8216d490eabbf0e98b385472b30af233652795/src/HasTags.php#L158-L166

as u can see both fires a `sync()`but for some reason i cant catch any, could there be some areas where the package doesnt operate/cover ?

**ps:**
if u need more info tell me, if there are some tests i could do on my part also tell me 👍

**Comment by fico7489** [comment]
Did you extend model in package and use PivotEventTrait ? 

https://github.com/spatie/laravel-permission/tree/0e0fba29758b892da94b62c5cb3250b1cc04fd41/src/Models

**Comment by ctf0** [comment]
yes ofcourse, but still nothing is logged, have u tried from ur end and it worked ?

**Comment by lewisf2001uk** [comment]
I might be off the mark, but it looks like both those packages use the MorphToMany relation which unfortunately this package doesn't currently support.

**Comment by ctf0** [comment]
@lewisf2001uk u r right 👍

**Comment by amadeann** [comment]
I found a relatively easy workaround for this:

https://github.com/amadeann/laravel-pivot/tree/2.1-with-morphs/

Basically, MorphToMany extends BelongsToMany relation, so we can make use of BelongsToManyCustom from this package. MorphToManyCustom won't have to have any extra logic, only use the code from BelongsToManyCustom, which is extracted to a trait. 

I will make a PR once I write tests for this.

**Comment by fico7489** [comment]
@amadeann  PR is merged, closing this one...
