### ISSUE TITLE
When syncing pivotAttached is called once per each key synced

### ISSUE THREAD

**Issue by kevin-barrientos** [fico7489/LaravelPivot#4]
Test on **Laravel 5.5** with **fico7489/laravel-pivot": "2.1.*"**

Docs says that `$model->sync([1, 2])` will display an output of `[1,2]` but instead I see an output of `[1]` and another of `[2]`. 

When you `dd($pivotIds)` the output is `[0 => 1]`. So the `$pivotIds` are indeed an array but the event is trigger once per each key.

**Comment by fico7489** [comment]
Actually, this example in docs supposes to be for attach() not sync (). Now I added tests for your case and docs are updated. Thanks for the catch. Documentation was problem not the code :)
