### ISSUE TITLE
Is the crud for the pivot models or for the models?

### ISSUE THREAD

**Issue by realtebo** [fico7489/LaravelPivot#40]
I've a Names table with many to many to Addresses 

So i've a adresses_names pivot 
This has id, address_id, name_id

I attached the trait to 'Name' model class.

But when fired the pivotAttached event I do not see the row id of the pivot table

**the model class**
log
App\Models\Name

**the relation name*
log
indirizzi

**the pivotIds**
log
array:1 [▼
  0 => 33
]

**the pivotIdAttributes**
log
array:1 [▼
  33 => []
]

IWhich is the most secure way to retrieve the (potentially more than one) pivot rows?

My goal is update some related columns in the same pivot table.

**Comment by amadeann** [comment]
When you define your `BelongsToMany` relationships, you should specify `id` in `withPivot` attributes. Not every pivot table has an id or an Eloquent model behind it, so pivot model ids (or other custom attibutes) can't be passed to events by default. 

In your example, you should do something like:

```
    public function addresses()
    {
        return $this->belongsToMany(Address::class, 'bill'->withPivot(['id']);
    }
```

**Comment by fico7489** [comment]
but inside $pivotIds are ids from pivot table
