### ISSUE TITLE
How to get Parent ID

### ISSUE THREAD

**Issue by bradenkeith** [fico7489/LaravelPivot#41]
Hi,

I am attempting to utilize this package to fire an event when 2 models are attached (email addresses attach to a project). Once they're attached, I'm hoping to fire an event.

I need the ID's of both models in order for my event to function as required. On projects, I am hoping to do something like this in my boot method. Obviously `$this->id` does not work because I'm out of object reference, but it demonstrates where I need the Project ID to go.

```
static::pivotAttached(function($model, $relationName, $pivotIds, $pivotIdsAttributes) {
	collect($pivotIds)->each(function($email_address_id){
		event(new ProjectHasNewEmailAddressWithAccessEvent($this->id, $email_address_id));
	});
});
```

Is this possible?

Thank you!

**Comment by fico7489** [comment]
I assume you have 3 tables : emails, projects and email_project, and 2 model Email and Project. One possible solution is to create EmailProject model with relations to email and project with that you can do something like this

	static::pivotAttached(function($model, $relationName, $pivotIds, $pivotIdsAttributes) {
		foreach($pivotIds as $pivotId){
			$pivot     = EmailProject::find($pivotId);
			$projectId = $pivot->project->id;
			$emailId   = $pivot->email->id;
			//
		}
	});
