### ISSUE TITLE
addObservableEvents versus overriding getObservableEvents

### ISSUE THREAD

**Issue by rickmacgillis** [fico7489/LaravelPivot#42]
I've noticed that `getObservableEvents` is missing the `retrieved` event. However, I'm not sure why you're overriding that method anyway when there's an `addObservableEvents` method to add your own events IN ADDITION TO the existing ones.

If this is due to it only becoming available in never Laravel versions, you might want to see if it makes sense to check if the `addObservableEvents` method exists and use that, then return the parent copy of `getObservableEvents` and if it doesn't exist, then use the method yourself and add your own methods to the resulting array before returning it.

**Comment by fico7489** [comment]
you are right, I will add addObservableEvents...thanks...

**Comment by fico7489** [comment]
added

**Comment by mfrischbutter** [comment]
Added in: https://github.com/fico7489/laravel-pivot/commit/d26c038e8eea097edb57b13743bd247d934393a2

Re-worked to use getObservableEvents in https://github.com/fico7489/laravel-pivot/commit/4cee9fe2668e54112c23c0b4d5d6d32db00f3c5f
