### ISSUE TITLE
Laravel 5.7 pivotAttached, pivotAttached 

### ISSUE THREAD

**Issue by T0miii** [fico7489/LaravelPivot#44]
Hello,

in Laravel 5.6 we were able to extract the pivottAttach events to the Observer class and the got triggered

Model:

`````
    protected static function boot()
    {
        parent::boot();

        self::observe(ContractObserver::class);
    }
`````

ContractObserver: 

``````
    public function pivotAttached($model, $relationName, $pivotIds, $pivotIdsAttributes)
    {
        $this->logTypeChanges($model, $pivotIds, self::ATTACHED);
    }

    public function pivotDetaching($model, $relationName, $pivotIds)
    {
        $this->logTypeChanges($model, $pivotIds, self::DETACHED);
    }
``````

This funcionality seems to be broken now in Laravel 5.7.

I can still register them in the boot method of the model, bit in its own observer we found it to be better.

Is there an explanation for this why this wont work anymore?

**Comment by fico7489** [comment]
I opened branch for 5.7 because someone asked me, it was a mistake because "orchestral/testbench" was not ready prepared for 5.7 and I could not run tests and check if something  is broken.
Now I updated docs that 5.7 is not ready yes. 
I will fix issue for 5.7 when I will have free time.

thanks!
