### ISSUE TITLE
Update coming for Laravel 5.7?

### ISSUE THREAD

**Issue by SonarSoftware** [fico7489/LaravelPivot#45]
Is this in production? Let me know if there's anything I can do to help otherwise, I use this package a lot and it's really helpful!

**Comment by fico7489** [comment]
it is still not added, you can submit PR if you want ...

**Comment by SonarSoftware** [comment]
OK, I'll start digging in :)

**Comment by SonarSoftware** [comment]
PR submitted.

**Comment by pabloguerrez** [comment]
I hope the PR will merged soon <3
