### ISSUE TITLE
event has triggered but data didn't sync

### ISSUE THREAD

**Issue by yang5664** [fico7489/LaravelPivot#5]
env: laravel 5.5.*
when i try to 
```
relation->sync([1,2]);
```
event has triggered but relation data didn't sync.

**Comment by fico7489** [comment]
@yang5664  I added tests for that you asked now and everything works fine.
https://github.com/fico7489/laravel-pivot/commit/177bfb7abda1c5bbbcac2bb0830d0372fd70322f
