### ISSUE TITLE
Does this work with Laravel Nova?

### ISSUE THREAD

**Issue by larsjanssen6** [fico7489/LaravelPivot#51]
Hi,

Thanks for this package. 

I use it in Laravel Nova, but it's not working. Maybe Laravel nova does
not use attach/detach?

Any idea?

**Comment by larsjanssen6** [comment]
Never mind. Used this: https://nova.laravel.com/docs/1.0/resources/relationships.html#belongstomany

**Comment by richardkeep** [comment]
I have used this package with Laravel Nova but it is not firing the event for BelongsToMany relationship. I want to sync my records with Algolia using Laravel Scout when I attach/detach items but it is no event is getting fired.
