### ISSUE TITLE
Laravel Nova support?

### ISSUE THREAD

**Issue by greggh** [fico7489/LaravelPivot#53]
I am attempting to use this in a project that is almost entirely done in Laravel Nova.

All of Nova is working great, but the events for pivot tables are not working. I have a belongsToMany relationship between two tables, websites, and technologies. Whenever a technology is attached to a website or detached, I need to do some other things.

I have it setup like described here on the github page:

In my App\Website model I have:

`use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
`
and:

`use PivotEventTrait;`

I have created a boot method for this:

`
protected static function boot()
    {
        parent::boot();

        static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            Log::info('pivotAttached' . $relationName . ' : ' . $pivotIds);
            dump('pivotAttached' . $relationName . ' : ' . $pivotIds);
        });

        static::pivotDetached(function ($model, $relationName, $pivotIds) {
            Log::info('pivotDetached' . $relationName . ' : ' . $pivotIds);
            dump('pivotAttached' . $relationName . ' : ' . $pivotIds);
        });
    }
`

and the relationship is defined like:

`    public function technologies()
    {
        return $this->belongsToMany('App\Technology')->withTimestamps();
    }
`

Nothing is logged and nothing is dumped when I go into my Websites page on Nova and use the Attach button on a Technology. The technology is attached, but the events don't fire.

**Comment by fico7489** [comment]
did you tried a package with with simple project without a laravel nova ?

**Comment by greggh** [comment]
Yeah, it works great on any operations that aren’t done through Nova. It only fails when you do the action in Nova. For some reason it doesn’t catch an attach or a detach when Nova does it via the Nova UI.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fico7489** [comment]
I would love to help but I think this is too broad question "package is not working with laravel nova", sincerely did not heard about "laravel nova" until now...

**Comment by greggh** [comment]
Laravel Nova is made by the actual Laravel team and was the big announcement at one of the last Laracons. It is the admin dashboard / crud tool, much like Horizon and Telescope are their other first-party tools. I am not sure how you are this good at Laravel and haven’t heard of it, but it is a big package and in heavy use.

It isn’t a broad issue at all. Your package literally does not work in Nova. At all. That isn’t broad. Nothing that your package offers actually works in Nova, so no examples or deeper explanations are needed. It does not work at all. I am not sure what else to say.

If I am not using Nova in my project, then your package is amazing and solves a real problem. It’s great. But if I have Nova installed, your package doesn’t do any of the things it is supposed to. None of the events happen.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
