### ISSUE TITLE
Getting syntax error while using the below statement in model

### ISSUE THREAD

**Issue by siva2507** [fico7489/LaravelPivot#54]
static::pivotDetached(function ($model, $relationName, $pivotIds) {
        echo 'pivotDetached';
        echo get_class($model);
        echo $relationName;
        print_r($pivotIds);
    });

**Comment by fico7489** [comment]
can you paste the error ?

**Comment by MattWohler** [comment]
Pretty sure he meant the following error as it's currently happening to me:

`"syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting function (T_FUNCTION) or const (T_CONST)"`

Placing the static pivot method as is shown in your Usage example; directly below my last relationship method of the Model.

EDIT:
Good ol' copy paste and 12 hours of straight coding will take you a minute to realize that the event listeners should be within the boot method of your Model.  Update your docs so I can be more lazy! 😆
