### ISSUE TITLE
laravel-pivot incompatible with official Laravel Telescope package

### ISSUE THREAD

**Issue by GregPeden** [fico7489/LaravelPivot#55]
The official Laravel package [Laravel Telescope](https://github.com/laravel/telescope) logs many server activities including Eloquent model events. It assumes that Eloquent event payloads follow the same pattern as the official Eloquent events included in the framework, however the payload from laravel-pivot is different. As a result, Telescope fails and throws an error at [this line](https://github.com/laravel/telescope/blob/1d02a40f0ab45a9d0e0ba8d02eb4768869967a10/src/Watchers/ModelWatcher.php#L36).

Arguably this is not laravel-pivot's concern, however since Telescope is an official framework package and this is not I thought you might like to consider this.

Below is an alternative ModelWatcher class which bypasses this problem by checking if the array property which Telescope is looking for exists, and if not, copy the 'model' property over so that an error is not thrown. Take care to note the assumed namespace for this example as others may not desire to create a "Watchers" folder just for this.
```php
namespace App\Watchers;

use \Laravel\Telescope\Watchers\ModelWatcher as PackageWatcher;

class ModelWatcher extends PackageWatcher {

    public function recordAction($event, $data)
    {
        //Catch and convert model events from some non-framework model event implementations such as
        //genealabs/laravel-model-caching and fico7489/laravel-pivot
        //Tested with fico7489/laravel-pivot v3.0.0 on 2019-02-02
        $modifiedData = $data;
        $modifiedData[0] = $modifiedData[0] ?? $modifiedData['model'];

        parent::recordAction($event, $modifiedData);
    }
}
```

Then [config/telescope.php](https://github.com/laravel/telescope/blob/1.0/config/telescope.php) sub in your modified ModelWatcher:
```php
...
        \App\Watchers\ModelWatcher::class => [
            'enabled' => env('TELESCOPE_MODEL_WATCHER', true),
            'events' => ['eloquent.*'],
        ],
...
```

**Comment by moshe-autoleadstar** [comment]
+1 to this issue.
one downside of the modified ModelWatcher is that appears as disabled on the frontend.
In order to fix that, you can override the ModelsController and point it to the overridden watcher
```
diff --git a/app/Http/Controllers/Telescope/ModelsController.php b/app/Http/Controllers/Telescope/ModelsController.php
new file mode 100644
index 0000000..2cb6a46
--- /dev/null
+++ b/app/Http/Controllers/Telescope/ModelsController.php
@@ -0,0 +1,13 @@
+<?php
+
+namespace App\Http\Controllers\Telescope;
+
+use App\Watchers\ModelWatcher;
+
+class ModelsController extends \Laravel\Telescope\Http\Controllers\ModelsController
+{
+    protected function watcher()
+    {
+        return ModelWatcher::class;
+    }
+}
diff --git a/app/Providers/TelescopeServiceProvider.php b/app/Providers/TelescopeServiceProvider.php
index e229eaf..30a3d78 100644
--- a/app/Providers/TelescopeServiceProvider.php
+++ b/app/Providers/TelescopeServiceProvider.php
@@ -2,6 +2,8 @@

 namespace App\Providers;

+use App\Http\Controllers\Telescope\ModelsController as OverriddenModelsController;
+use Laravel\Telescope\Http\Controllers\ModelsController as OriginalModelsController;
 use Laravel\Telescope\Telescope;
 use Illuminate\Support\Facades\Gate;
 use Laravel\Telescope\IncomingEntry;
@@ -20,6 +22,8 @@ class TelescopeServiceProvider extends TelescopeApplicationServiceProvider

         $this->hideSensitiveRequestDetails();

+        $this->app->bind(OriginalModelsController::class, OverriddenModelsController::class);
+
         Telescope::filter(function (IncomingEntry $entry) {
             if ($this->app->isLocal()) {
                 return true;
```

**Comment by GregPeden** [comment]
Here is an alternative implementation of the custom watcher which does not replace the existing Telescope code so that it will be more resilient through Telescope code base changes.

```php
use \Laravel\Telescope\Watchers\ModelWatcher as PackageWatcher;

class ModelWatcher extends PackageWatcher {

    public function recordAction($event, $data)
    {
        //Catch and convert model events from some non-framework model event implementations such as
        //genealabs/laravel-model-caching and fico7489/laravel-pivot
        //Tested with fico7489/laravel-pivot v3.0.0 on 2019-02-02
        $modifiedData = $data;
        $modifiedData[0] = $modifiedData[0] ?? $modifiedData['model'];

        parent::recordAction($event, $modifiedData);
    }
}
```

**Comment by fico7489** [comment]
It is really not possible to test all laravel official packages with my package and maintain my package to work with all of them...

**Comment by moshe-autoleadstar** [comment]
That's why we love open source and pull requests 😉 https://github.com/fico7489/laravel-pivot/pull/50
