### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by joeelia** [fico7489/LaravelPivot#56]
`src/Traits/ExtendFireModelEventTrait.php:36` has the following error:

`Call to undefined method Illuminate\Events\Dispatcher::fire()`

With Larval 5.8 fire() is replaced with dispatch(). Not sure how to fix it, is this something that the package can support?

Source:
https://github.com/laravel/framework/pull/26392
https://laravel.com/docs/5.8/upgrade

**Comment by joeelia** [comment]
This issue can be closed when [PR#57](https://github.com/fico7489/laravel-pivot/pull/57) is committed to master branch.

**Comment by fico7489** [comment]
an issue is fixed!

**Comment by LeonAlvarez** [comment]
Laravel 5.8 already supports pivot events

**Comment by mikebronner** [comment]
@LeonAlvarez I couldn't find anything in the documentation about this. (I haven't dived into the source code yet.) Would you share a link where this is documented? Thanks :)

**Comment by joeelia** [comment]
@mikebronner https://laravel.com/docs/5.8/releases#laravel-5.8 section **Intermediate Table / Pivot Model Events**

**Comment by mikebronner** [comment]
@joeelia Thanks for posting that.

@LeonAlvarez I don't believe this functionality replaces the functionality of this package, as you need to create models for all pivot tables for Laravel to report the events, so if you update a legacy app that doesn't have those pivot models defined, you still won't get any events.
