### ISSUE TITLE
Events for Spatie laravel-permission

### ISSUE THREAD

**Issue by lucianobosco** [fico7489/LaravelPivot#64]
I'm trying to implement this package with Spatie permissions but no luck so far.
I'm using a custom Role model with `PivotEventTrait` but nothing happens when `$role->syncPermissions()` is performed.

This is my current Role model, nothing special...
```
<?php
namespace App;

use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
use Spatie\Permission\Models\Role as Roles;

class Role extends Roles
{
    use PivotEventTrait;
    protected $table    = 'roles';
    protected $fillable = ['name','title','guard_name'];
}
```

My RoleController update function extract:
```
public function update(UpdateRole $request)
    {
            ............
            $role->syncPermissions($permissions);
            ............
    }
```

FYI, `syncPermissions` provided by Spatie's package make use of the detach event:
```
public function syncPermissions(...$permissions)
    {
        $this->permissions()->detach();
        return $this->givePermissionTo($permissions);
    }
```
Any help will be appreciated.
Thanks in advance

**Comment by lucianobosco** [comment]
Ok, my bad, I forgot to add the events to the observer that I'm using:
```
pivotAttaching, pivotAttached
pivotDetaching, pivotDetached,
pivotUpdating, pivotUpdated
```
But now, instead of listening attach and detach events, which will cause a lot of events, is there a way to listen for `sync` event? like `pivotSync`

**Comment by fico7489** [comment]
when you call sync() and something is added or removed correlative events are dispathed (pivotAttaching, pivotAttached, pivotDetaching, pivotDetached,)
