### ISSUE TITLE
Unexpected output when attaching using array notation with attributes

### ISSUE THREAD

**Issue by lewisf2001uk** [fico7489/LaravelPivot#8]
Unexpected output on the fired events for the pivot ids.
For example, when attaching using the below notation:
`
$user->roles()->attach([
    1 => ['expires' => $expires],
    2 => ['expires' => $expires]
]);
`

See: https://laravel.com/docs/5.5/eloquent-relationships#many-to-many

Receiving :
`
array:2 [
  1 => array:1 [
    "value" => 123
  ],
  2 => array:1 [
    "value" => 456
  ]
]
`

Expecting:
`
array:2 [
  0 => 1,
  1 => 2
]
`

This could cause issues did to the id being the key of the array instead of the value.
The reason is that the attributes are in an array with the ids when passed to the attach method.

**Comment by lewisf2001uk** [comment]
I am currently working on a fix for this.
I will submit a pull request for you to look over when I've finished the fix.

**Comment by fico7489** [comment]
@lewisf2001uk  yes, tests don't cover updates with additional data, thanks for the catch, I am waiting for PR then...

**Comment by fico7489** [comment]
changes will be merged soon https://github.com/fico7489/laravel-pivot/pull/10
