### ISSUE TITLE
Not saved attributes i DB after adding pivot attributes in pivotAttaching event

### ISSUE THREAD

**Issue by hohanov** [fico7489/LaravelPivot#80]
I am using this plugin in Laravel 6 project. (Please excuse my bad english 🙏).
I have a problem with pivotAttaching event. The event is fired, but after changing the pivot attributes (add 'created_by'), the attributes are not saved to the DB. 
`SQLSTATE[HY000]: General error: 1364 Field 'created_by' doesn't have a default value (SQL: insert into `links` (`detail_linked`, `detail_main`) values (7, 19))`
The screenshot shows the added attributes at the end of the event execution (debug mode).
![debug](https://user-images.githubusercontent.com/63554058/136442452-182755e0-d1f9-4187-9df4-77cbdfc2dc0c.PNG)
(full Response with error https://gist.github.com/overclocked555/89e3955ec866f85003c6eccc65631232)
**app\Http\Controllers\DetailController.php**
```
...
$detail->accessories()->attach($id);
...
```
**app\Detail.php**
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;

class detail extends Model
{
    use PivotEventTrait; 
	
    protected $table = 'details';

    protected $fillable = [
        'name',
    ];
    
    public function accessories()
    {
        return $this->belongsToMany('App\Detail', 'links', 'detail_main', 'detail_linked');
    }

    public function is_accessory_for()
    {
        return $this->belongsToMany('App\Detail', 'links', 'detail_linked', 'detail_main');
    }

    protected static function boot() {
        parent::boot();
    
        static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            foreach ($pivotIdsAttributes as $id => &$attributes) {
                if (@\Auth::check() && @\Auth::user()->id) {
                    $attributes['created_by'] = \Auth::user()->id;
                }
                $attributes['created_at'] = Carbon\Carbon::now();                
            }
        });
    }
}
```
**app\Link.php**
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{    
    protected $table = 'links';

    protected $fillable = [
        'detail_linked', 
        'detail_main'
    ];
}
```

**Comment by fico7489** [comment]
hey, this package do not cover changing the data which will be stored in the event(for now), there are just events with the data what is changed
