### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by schonhoff** [fico7489/LaravelPivot#81]
Hello,

will this package be updated for Laravel 9 support?

**Comment by samuelhowell** [comment]
Update on Laravel 9 support?

**Comment by PHLAK** [comment]
@samuelhowell I [opened a PR](https://github.com/fico7489/laravel-pivot/pull/85) but it seems like this package already _implicitly_ works with Laravel 9 (due to a poor composer constaraint in v3.0.3).

**Comment by samuelhowell** [comment]
@PHLAK yeah I saw that. That's how I've currently got it working while testing. Thanks for sharing.

**Comment by deffjay** [comment]
I'm just adding additional support for this request. I was able to get it going, but for the sketchy composer reason described above

**Comment by titantwentyone** [comment]
I needed this functionality and came across this package from the comments raised in https://github.com/laravel/framework/issues/2303. Do you think this could/should be reworked and raised as a PR for Laravel itself rather than a package? The code itself is pretty unobtrusive and I feel it should be part of the core.

**Comment by schonhoff** [comment]
Maybe you can provide a PR? :-) Would upvote for it.

**Comment by PHLAK** [comment]
He @schonhoff, anyway we can get https://github.com/fico7489/laravel-pivot/pull/85 reviewed?

**Comment by mattvb91** [comment]
ping @fico7489 https://github.com/fico7489/laravel-pivot/pull/85

**Comment by schonhoff** [comment]
Just got merged. Maybe someone can open a PR for Laravel 10? It should be included for the next month release.
