### ISSUE TITLE
Bump to Laravel 11?

### ISSUE THREAD

**Issue by cheesegrits** [fico7489/LaravelPivot#92]
Any chance you could get this bumped to Laravel 11?

**Comment by Jxckaroo** [comment]
+1

Opened a PR for it [here](https://github.com/fico7489/laravel-pivot/pull/93)

**Comment by spawnia** [comment]
Thank you @Jxckaroo for the PR and thank you @fico7489 for merging and providing this package. Can you publish a release that includes the update?

**Comment by fico7489** [comment]
done!
